language: rust
cache: cargo
sudo: false

branches:
  only:
  - master

matrix:
  include:
    - os: linux
      dist: trusty
      rust: stable
    - os: linux
      dist: trusty
      rust: nightly
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
    - os: linux
      dist: trusty
      rust: stable
      env:
        - TARGET=arm-linux-gnueabi
        - RUST_TARGET=arm-unknown-linux-gnueabi
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-armel-cross
            - libc6-dev-armel-cross
    - os: linux
      dist: trusty
      rust: stable
      env:
        - TARGET=aarch64-linux-gnu
        - RUST_TARGET=aarch64-unknown-linux-gnu
      addons:
        apt:
          packages:
            - gcc-aarch64-linux-gnu
            - libc6-arm64-cross
            - libc6-dev-arm64-cross
    - os: linux
      dist: trusty
      rust: stable
      env:
        - TARGET=arm-linux-androideabi
        - RUST_TARGET=arm-linux-androideabi
    - os: linux
      dist: trusty
      rust: stable
      env:
        - TARGET=aarch64-linux-android
        - RUST_TARGET=aarch64-linux-android

install:
  - if [ x"$TARGET" = "xarm-linux-androideabi" ] || [ x"$TARGET" = "xaarch64-linux-android" ]; then
      wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip;
      unzip android-ndk-r16b-linux-x86_64.zip  2>&1 >/dev/null;

      if [[ x"$TARGET" = "xarm-linux-androideabi" ]]; then
        ./android-ndk-r16b/build/tools/make_standalone_toolchain.py --arch arm --api 19 --install-dir $PWD/cross;
      else
        ./android-ndk-r16b/build/tools/make_standalone_toolchain.py --arch arm64 --api 21 --install-dir $PWD/cross;
      fi

      export PATH="$PATH:$PWD/cross/bin";
    fi

script:
  - autoreconf -ivf
  - if [[ x"$TARGET" == "x" ]]; then
      ./configure;
    else
      rustup target add $RUST_TARGET;
      ./configure --host=$TARGET --enable-rusthost=$RUST_TARGET --disable-examples;
    fi
  - make
  - if [[ x"$TARGET" == "x" ]]; then ./examples/client/client www.google.com ; fi
  - if [[ x"$TARGET" == "x" ]]; then RUST_BACKTRACE=1 cargo test ; fi
  - if [[ x"$TARGET" == "x" ]]; then ( cd bogo && ./runme ) ; fi
