[package]
name = "mesalink"
version = "0.0.1"
authors = ["Yiming Jing <jingyiming@baidu.com>"]
description = "Mesalink is an OpenSSL-compatible TLS library based on Rustls and Ring"
build = "build.rs"

[lib]
name = "mesalink"
crate-type = ["cdylib", "staticlib"]

[features]
default = ["error_strings"]
error_strings = []
tls13_draft = []

[dependencies]
rustls = "0.11.0"
webpki-roots = "0.13.0"
libc = "0.2"
lazy_static = "0.2.*"
