[package]
name = "mesalink"
version = "0.1.0"
authors = ["The MesaLink Project Contributors"]
license = "BSD-3-Clause"
readme = "README.md"
description = "MesaLink is a memory-safe and OpenSSL-compatible TLS library based on Rustls and Ring."
categories = ["network-programming"]
build = "build.rs"

[lib]
name = "mesalink"
crate-type = ["cdylib", "staticlib"]

[features]
error_strings = ["rustls/logging"]
tls13 = ["rustls/tls13"]
aesgcm = ["rustls/aesgcm"]
chachapoly = ["rustls/chachapoly"]
x25519 = ["rustls/x25519"]
ecdh = ["rustls/ecdh"]
ecdsa = ["rustls/ecdsa"]

[dependencies]
rustls = { version = "0.12.0", default-features = false }
ring = { version = "0.13.0-alpha", features = ["rsa_signing", ] }
webpki = "0.18.0-alpha"
webpki-roots = "0.14.0"
libc = "0.2"
lazy_static = "1.0.0"

[patch.crates-io]
rustls = { path = "./rustls" }

[profile.release]
opt-level = "z"
lto = true
panic = "abort"
