[package]
name = "mesalink"
version = "0.1.0"
authors = ["Yiming Jing <jingyiming@baidu.com>"]
license = "BSD-3-Clause"
description = "MesaLink is an OpenSSL-compatible TLS library based on Rustls and Ring."
categories = ["network-programming"]
build = "build.rs"

[lib]
name = "mesalink"
crate-type = ["cdylib", "staticlib"]

[features]
default = ["error_strings"]
error_strings = []
tls13_draft = []

[dependencies]
rustls = {git = "https://github.com/ctz/rustls", rev = "f22c9ba"}
ring = { version = "0.12.1", features = ["rsa_signing"] }
webpki = { git = "https://github.com/briansmith/webpki" }
webpki-roots = { git = "https://github.com/briansmith/webpki-roots", branch = "webpki-github" }
libc = "0.2"
lazy_static = "1.0.0"
